"""Tests for maxfi_pricing.py (pure valuation math) and
maxfi_anchor_prices.py (anchor USD resolver). Offline, no network, no
database — maxfi_pricing.py takes everything as arguments, and the
anchor resolver tests inject a stub fetcher.
"""

import json
import math
import os
from datetime import datetime, timedelta, timezone
from decimal import Decimal

import pytest

import maxfi_anchor_prices as ap
import maxfi_math as mm
import maxfi_pricing as mp

@pytest.fixture(autouse=True)
def _clear_anchor_price_cache():
    """maxfi_anchor_prices keeps a module-level in-memory cache by design
    (mirrors the real resolver's own persistence across requests) - clear
    it before each test so tests are independent of execution order and
    don't rely on well-separated `now` values to avoid collisions."""
    ap._price_cache.clear()
    yield
    ap._price_cache.clear()


Q96 = 2 ** 96


def tick_to_sqrt_price_x96(tick):
    return int((1.0001 ** (tick / 2)) * Q96)


def price_to_tick(price_decimal_adjusted, decimals0, decimals1):
    raw_price = price_decimal_adjusted / (10 ** (decimals0 - decimals1))
    return math.log(raw_price) / math.log(1.0001)


# ── Real #757217 fixture (Phase D.1) ──────────────────────────────────────
#
# Phase D's fixture for this position was RECONSTRUCTED from two surviving
# derived numbers (a price range and a range-width percentage) - it was
# never a real chain capture, so it could not detect a systematically wrong
# formula (a fixture generated by the formula under test agrees with that
# formula whether or not it's correct). This is a REAL capture: block
# 47938836 on Robinhood Chain, taken alongside the live maxfi.tech card for
# the same position, with expected outputs computed independently from raw
# chain state and reconciled against that card. See
# tests/fixtures/maxfi_757217_block47938836.json for the full capture and
# its _readme/card_cross_check notes.

_FIXTURE_PATH = os.path.join(os.path.dirname(__file__), "fixtures", "maxfi_757217_block47938836.json")

with open(_FIXTURE_PATH) as _f:
    FIXTURE_757217 = json.load(_f)

_F_DEC0 = FIXTURE_757217["token0"]["decimals"]
_F_DEC1 = FIXTURE_757217["token1"]["decimals"]
_F_SQRT_PRICE_X96 = int(FIXTURE_757217["slot0"]["sqrtPriceX96"])
_F_CURRENT_TICK = int(FIXTURE_757217["slot0"]["tick"])
_F_TICK_LOWER = int(FIXTURE_757217["npm_position"]["tickLower"])
_F_TICK_UPPER = int(FIXTURE_757217["npm_position"]["tickUpper"])
_F_LIQUIDITY = int(FIXTURE_757217["npm_position"]["liquidity"])
_F_FG_GLOBAL0 = int(FIXTURE_757217["fee_growth_global_0_x128"])
_F_FG_GLOBAL1 = int(FIXTURE_757217["fee_growth_global_1_x128"])
_F_FG_OUT0_LOWER = int(FIXTURE_757217["ticks_lower"]["feeGrowthOutside0X128"])
_F_FG_OUT1_LOWER = int(FIXTURE_757217["ticks_lower"]["feeGrowthOutside1X128"])
_F_FG_OUT0_UPPER = int(FIXTURE_757217["ticks_upper"]["feeGrowthOutside0X128"])
_F_FG_OUT1_UPPER = int(FIXTURE_757217["ticks_upper"]["feeGrowthOutside1X128"])
_F_FG_INSIDE0_LAST = int(FIXTURE_757217["npm_position"]["feeGrowthInside0LastX128"])
_F_FG_INSIDE1_LAST = int(FIXTURE_757217["npm_position"]["feeGrowthInside1LastX128"])
_F_TOKENS_OWED0 = int(FIXTURE_757217["npm_position"]["tokensOwed0"])
_F_TOKENS_OWED1 = int(FIXTURE_757217["npm_position"]["tokensOwed1"])
_F_CUM_FEES0 = int(FIXTURE_757217["vault_position"]["cumulativeFees0"])
_F_CUM_FEES1 = int(FIXTURE_757217["vault_position"]["cumulativeFees1"])
_F_EXPECTED = FIXTURE_757217["expected"]

# Pinned exact integers (STEP 1: "compute the exact integers yourself in the
# test and pin them as literals once confirmed, so future runs are exact
# rather than tolerance-based"). Confirmed against _F_EXPECTED below once,
# then hardcoded so a future regression shows as a literal mismatch.
_F_UNCOLLECTED0_RAW = 9637350593082893
_F_UNCOLLECTED1_RAW = 1363925805040744371105


def test_fixture_pinned_integers_match_expected_raw_values():
    # Sanity-check the pinned literals above against the fixture's own
    # recorded raw expectations, so the two can't silently drift apart.
    assert _F_UNCOLLECTED0_RAW == int(_F_EXPECTED["uncollected0_raw"])
    assert _F_UNCOLLECTED1_RAW == int(_F_EXPECTED["uncollected1_raw"])


def test_pool_price_token1_per_token0_against_757217_fixture():
    result = mp.pool_price_token1_per_token0(_F_SQRT_PRICE_X96, _F_DEC0, _F_DEC1)
    assert result == pytest.approx(_F_EXPECTED["pool_price_token1_per_token0"], rel=1e-6)


def test_price_range_against_757217_fixture():
    price_lower = mm.tick_to_price(_F_TICK_LOWER, _F_DEC0, _F_DEC1)
    price_upper = mm.tick_to_price(_F_TICK_UPPER, _F_DEC0, _F_DEC1)
    assert price_lower == pytest.approx(_F_EXPECTED["price_lower"], rel=1e-6)
    assert price_upper == pytest.approx(_F_EXPECTED["price_upper"], rel=1e-6)


def test_range_percent_against_757217_fixture():
    result = mm.range_percent(_F_TICK_LOWER, _F_TICK_UPPER, _F_DEC0, _F_DEC1)
    assert result == pytest.approx(_F_EXPECTED["range_percent"], rel=1e-6)


def test_liquidity_to_amounts_against_757217_fixture():
    amount0_raw, amount1_raw = mm.liquidity_to_amounts(
        _F_LIQUIDITY, _F_TICK_LOWER, _F_TICK_UPPER, _F_CURRENT_TICK, _F_SQRT_PRICE_X96
    )
    amount0 = amount0_raw / (10 ** _F_DEC0)
    amount1 = amount1_raw / (10 ** _F_DEC1)
    assert amount0 == pytest.approx(_F_EXPECTED["amount0"], rel=1e-9)
    assert amount1 == pytest.approx(_F_EXPECTED["amount1"], rel=1e-9)


def test_uncollected_fees_against_757217_fixture():
    fg_inside0 = mm.fee_growth_inside(
        _F_CURRENT_TICK, _F_TICK_LOWER, _F_TICK_UPPER, _F_FG_GLOBAL0, _F_FG_OUT0_LOWER, _F_FG_OUT0_UPPER
    )
    fg_inside1 = mm.fee_growth_inside(
        _F_CURRENT_TICK, _F_TICK_LOWER, _F_TICK_UPPER, _F_FG_GLOBAL1, _F_FG_OUT1_LOWER, _F_FG_OUT1_UPPER
    )
    uncollected0_raw = mm.uncollected_fees(_F_LIQUIDITY, fg_inside0, _F_FG_INSIDE0_LAST, _F_TOKENS_OWED0)
    uncollected1_raw = mm.uncollected_fees(_F_LIQUIDITY, fg_inside1, _F_FG_INSIDE1_LAST, _F_TOKENS_OWED1)

    # Exact integer match against the pinned literals - not a tolerance.
    assert uncollected0_raw == _F_UNCOLLECTED0_RAW
    assert uncollected1_raw == _F_UNCOLLECTED1_RAW

    uncollected0 = uncollected0_raw / (10 ** _F_DEC0)
    uncollected1 = uncollected1_raw / (10 ** _F_DEC1)
    assert uncollected0 == pytest.approx(_F_EXPECTED["uncollected0"], rel=1e-6)
    assert uncollected1 == pytest.approx(_F_EXPECTED["uncollected1"], rel=1e-6)


def test_collected_fees_against_757217_fixture_exact():
    collected0 = _F_CUM_FEES0 / (10 ** _F_DEC0)
    collected1 = _F_CUM_FEES1 / (10 ** _F_DEC1)
    assert collected0 == _F_EXPECTED["collected0"]
    assert collected1 == _F_EXPECTED["collected1"]


def test_card_cross_check_uncollected_usd_within_one_percent():
    # ASSERT (per STEP 1): uncollected USD is within 1% of the card's $46.50
    # when priced at eth_usd=2502.92 with STONKBROKER derived from pool rate.
    card = FIXTURE_757217["card_cross_check"]
    eth_usd = card["eth_usd_at_capture"]
    derived = mp.derive_usd_prices(
        "WETH", "STONKBROKER", "token0", eth_usd, _F_SQRT_PRICE_X96, _F_DEC0, _F_DEC1
    )
    uncollected0 = _F_UNCOLLECTED0_RAW / (10 ** _F_DEC0)
    uncollected1 = _F_UNCOLLECTED1_RAW / (10 ** _F_DEC1)
    uncollected_usd = uncollected0 * derived["token0_usd"] + uncollected1 * derived["token1_usd"]
    assert uncollected_usd == pytest.approx(card["uncollected_usd_card"], rel=0.01)


def test_card_cross_check_collected_usd_known_divergence():
    # ASSERT (per STEP 1): our current-price collected USD is 24.16 +/- 1%.
    # This intentionally does NOT match the card's $20.52 - see STEP 3 /
    # maxfi_pricing.py's module docstring for why that divergence is
    # expected and not something to chase.
    card = FIXTURE_757217["card_cross_check"]
    eth_usd = card["eth_usd_at_capture"]
    derived = mp.derive_usd_prices(
        "WETH", "STONKBROKER", "token0", eth_usd, _F_SQRT_PRICE_X96, _F_DEC0, _F_DEC1
    )
    collected0 = _F_CUM_FEES0 / (10 ** _F_DEC0)
    collected1 = _F_CUM_FEES1 / (10 ** _F_DEC1)
    collected_usd = collected0 * derived["token0_usd"] + collected1 * derived["token1_usd"]
    assert collected_usd == pytest.approx(card["collected_usd_computed_current_price"], rel=0.01)


# ── STEP 2: fee-growth branch selection at all three tick positions ─────
# The single highest-risk item in Phase D: the lower tick uses
# feeGrowthOutside directly when current_tick is AT OR ABOVE it, and the
# upper tick uses it directly when current_tick is BELOW it. Inverting
# either branch on this fixture is not a subtle bug - it produces ~6e40
# WETH instead of 0.0096 (see test below).

def test_fee_growth_inside_current_tick_below_range():
    # Synthetic tick position (never occurred on this position) - assert
    # only that the correct branch is taken and the result is sane, not an
    # invented dollar value.
    below_tick = _F_TICK_LOWER - 100
    inside0 = mm.fee_growth_inside(
        below_tick, _F_TICK_LOWER, _F_TICK_UPPER, _F_FG_GLOBAL0, _F_FG_OUT0_LOWER, _F_FG_OUT0_UPPER
    )
    assert 0 <= inside0 <= mm.MASK_256
    # below_tick < tick_lower -> below = global - outside_lower (mod 2**256)
    expected_below = (_F_FG_GLOBAL0 - _F_FG_OUT0_LOWER) & mm.MASK_256
    # below_tick < tick_upper -> above = outside_upper directly
    expected_above = _F_FG_OUT0_UPPER & mm.MASK_256
    expected_inside = (_F_FG_GLOBAL0 - expected_below - expected_above) & mm.MASK_256
    assert inside0 == expected_inside


def test_fee_growth_inside_current_tick_inside_range_real_case():
    # The actual on-chain case for this position - checked against the
    # fully independently verified expected values via
    # test_uncollected_fees_against_757217_fixture above.
    inside0 = mm.fee_growth_inside(
        _F_CURRENT_TICK, _F_TICK_LOWER, _F_TICK_UPPER, _F_FG_GLOBAL0, _F_FG_OUT0_LOWER, _F_FG_OUT0_UPPER
    )
    assert 0 <= inside0 <= mm.MASK_256
    uncollected0_raw = mm.uncollected_fees(_F_LIQUIDITY, inside0, _F_FG_INSIDE0_LAST, _F_TOKENS_OWED0)
    assert uncollected0_raw == _F_UNCOLLECTED0_RAW


def test_fee_growth_inside_current_tick_above_range():
    above_tick = _F_TICK_UPPER + 100
    inside0 = mm.fee_growth_inside(
        above_tick, _F_TICK_LOWER, _F_TICK_UPPER, _F_FG_GLOBAL0, _F_FG_OUT0_LOWER, _F_FG_OUT0_UPPER
    )
    assert 0 <= inside0 <= mm.MASK_256
    # above_tick >= tick_lower -> below = outside_lower directly
    expected_below = _F_FG_OUT0_LOWER & mm.MASK_256
    # above_tick >= tick_upper -> above = global - outside_upper (mod 2**256)
    expected_above = (_F_FG_GLOBAL0 - _F_FG_OUT0_UPPER) & mm.MASK_256
    expected_inside = (_F_FG_GLOBAL0 - expected_below - expected_above) & mm.MASK_256
    assert inside0 == expected_inside


def test_fee_growth_inside_inverted_upper_branch_would_be_catastrophically_wrong():
    # Regression guard matching the spec's own warning: inverting the
    # upper-tick branch on this fixture doesn't produce a subtly-wrong
    # number, it produces something on the order of 1e40 WETH. If this test
    # ever fails, someone swapped the upper-tick condition.
    correct_inside0 = mm.fee_growth_inside(
        _F_CURRENT_TICK, _F_TICK_LOWER, _F_TICK_UPPER, _F_FG_GLOBAL0, _F_FG_OUT0_LOWER, _F_FG_OUT0_UPPER
    )

    def inverted_fee_growth_inside(current_tick, tick_lower, tick_upper, fg_global, fg_out_lower, fg_out_upper):
        below = fg_out_lower if current_tick >= tick_lower else (fg_global - fg_out_lower) & mm.MASK_256
        # Inverted: should be `current_tick < tick_upper`, not `>=`.
        above = fg_out_upper if current_tick >= tick_upper else (fg_global - fg_out_upper) & mm.MASK_256
        return (fg_global - below - above) & mm.MASK_256

    inverted_inside0 = inverted_fee_growth_inside(
        _F_CURRENT_TICK, _F_TICK_LOWER, _F_TICK_UPPER, _F_FG_GLOBAL0, _F_FG_OUT0_LOWER, _F_FG_OUT0_UPPER
    )
    assert inverted_inside0 != correct_inside0

    inverted_uncollected0_raw = mm.uncollected_fees(
        _F_LIQUIDITY, inverted_inside0, _F_FG_INSIDE0_LAST, _F_TOKENS_OWED0
    )
    inverted_amount0 = inverted_uncollected0_raw / (10 ** _F_DEC0)
    # The correct answer is ~0.0096 WETH; the inverted branch is off by
    # roughly 42 orders of magnitude.
    assert inverted_amount0 > 1e30


# ── derive_usd_prices: both directions (the highest-value test here) ────

def test_derive_usd_prices_anchor_is_token0():
    # WETH(18)/USDC(6), token0=WETH is the anchor at $2500.
    price_t1_per_t0 = 2500.0  # USDC per WETH
    sqrt_price_x96 = int(Q96 * Decimal(price_t1_per_t0 * 10 ** (6 - 18)).sqrt())
    result = mp.derive_usd_prices("WETH", "USDC", "token0", 2500.0, sqrt_price_x96, 18, 6)
    assert result["token0_usd"] == 2500.0
    assert result["token1_usd"] == pytest.approx(1.0, rel=0.01)
    assert result["derived_side"] == "token1"


def test_derive_usd_prices_anchor_is_token1():
    # USDC(6)/WETH(18) — token0/token1 order flipped (address-sorted, not
    # semantic) — anchor is now token1 (WETH) at $2500.
    price_t1_per_t0 = 1 / 2500.0  # WETH per USDC
    sqrt_price_x96 = int(Q96 * Decimal(price_t1_per_t0 * 10 ** (18 - 6)).sqrt())
    result = mp.derive_usd_prices("USDC", "WETH", "token1", 2500.0, sqrt_price_x96, 6, 18)
    assert result["token1_usd"] == 2500.0
    assert result["token0_usd"] == pytest.approx(1.0, rel=0.01)
    assert result["derived_side"] == "token0"


def test_derive_usd_prices_directions_are_not_accidentally_symmetric():
    # A regression guard against the exact failure mode the spec warns
    # about: an inversion bug produces a PLAUSIBLE-LOOKING wrong number
    # (e.g. multiplying instead of dividing) rather than crashing. Assert
    # the token0-anchor and token1-anchor results for the SAME pool rate
    # are reciprocal-shaped, not identical.
    sqrt_price_x96 = tick_to_sqrt_price_x96(round(price_to_tick(2500.0, 18, 6)))
    as_token0 = mp.derive_usd_prices("A", "B", "token0", 2500.0, sqrt_price_x96, 18, 6)
    as_token1 = mp.derive_usd_prices("A", "B", "token1", 2500.0, sqrt_price_x96, 18, 6)
    # If anchor is token0 ($2500), the derived token1 price is small (~1).
    # If the SAME $2500 anchor is instead attached to token1, the derived
    # token0 price is huge (~2500 * 2500) - these must differ enormously;
    # an inversion bug would make them coincidentally close.
    assert as_token0["token1_usd"] < 10
    assert as_token1["token0_usd"] > 1_000_000


def test_derive_usd_prices_invalid_anchor_side_raises():
    with pytest.raises(ValueError):
        mp.derive_usd_prices("A", "B", "sideways", 2500.0, tick_to_sqrt_price_x96(0), 18, 6)


def test_derive_usd_prices_anchor_price_none_propagates_none():
    result = mp.derive_usd_prices("A", "B", "token0", None, tick_to_sqrt_price_x96(0), 18, 6)
    assert result["token0_usd"] is None
    assert result["token1_usd"] is None


# ── Decimals asymmetry ────────────────────────────────────────────────────

def test_decimals_asymmetry_18_6_vs_6_18():
    tick = round(price_to_tick(2500.0, 18, 6))
    sqrt_price_x96 = tick_to_sqrt_price_x96(tick)
    price_18_6 = mp.pool_price_token1_per_token0(sqrt_price_x96, 18, 6)
    assert price_18_6 == pytest.approx(2500.0, rel=0.001)

    # Same raw tick, decimals REVERSED (6, 18): the 10**(d0-d1) adjustment
    # must apply in the opposite direction, producing a wildly different
    # (not just sign-flipped) number - 10**12 apart, not 1/2500.
    price_6_18 = mp.pool_price_token1_per_token0(sqrt_price_x96, 6, 18)
    assert price_6_18 == pytest.approx(2500.0 * 10 ** (6 - 18) / 10 ** (18 - 6), rel=0.001)
    assert price_6_18 != pytest.approx(price_18_6, rel=0.5)


# ── Division-by-zero guards: assert None specifically, not falsiness ────

def test_days_held_zero_gives_none_usd_per_day():
    now = datetime(2025, 1, 1, tzinfo=timezone.utc)
    result = mp.compute_performance(
        current_value_usd=1000.0, initial_value_usd=900.0,
        uncollected_usd=10.0, collected_usd=5.0,
        first_seen_at_utc=now, now_utc=now,  # zero elapsed time
    )
    assert result["days_held"] == 0
    assert result["usd_per_day"] is None
    assert result["usd_per_day"] is not 0.0  # noqa: F632 - explicit identity, not truthiness


def test_days_held_negative_gives_none_usd_per_day():
    now = datetime(2025, 1, 1, tzinfo=timezone.utc)
    later_first_seen = now + timedelta(days=1)  # first_seen AFTER now - malformed input
    result = mp.compute_performance(
        current_value_usd=1000.0, initial_value_usd=900.0,
        uncollected_usd=10.0, collected_usd=5.0,
        first_seen_at_utc=later_first_seen, now_utc=now,
    )
    assert result["days_held"] < 0
    assert result["usd_per_day"] is None


def test_current_value_zero_gives_none_apr():
    now = datetime(2025, 1, 1, tzinfo=timezone.utc)
    first_seen = now - timedelta(days=30)
    result = mp.compute_performance(
        current_value_usd=0.0, initial_value_usd=900.0,
        uncollected_usd=10.0, collected_usd=5.0,
        first_seen_at_utc=first_seen, now_utc=now,
    )
    assert result["apr_percent"] is None


def test_current_value_none_gives_none_apr():
    now = datetime(2025, 1, 1, tzinfo=timezone.utc)
    first_seen = now - timedelta(days=30)
    result = mp.compute_performance(
        current_value_usd=None, initial_value_usd=900.0,
        uncollected_usd=10.0, collected_usd=5.0,
        first_seen_at_utc=first_seen, now_utc=now,
    )
    assert result["apr_percent"] is None
    assert result["pnl_usd"] is None  # current_value_usd unavailable


def test_initial_value_none_gives_none_pnl():
    now = datetime(2025, 1, 1, tzinfo=timezone.utc)
    first_seen = now - timedelta(days=30)
    result = mp.compute_performance(
        current_value_usd=1000.0, initial_value_usd=None,
        uncollected_usd=10.0, collected_usd=5.0,
        first_seen_at_utc=first_seen, now_utc=now,
    )
    assert result["pnl_usd"] is None
    assert any("initial_value_usd is null" in n for n in result["notes"])


def test_first_seen_at_none_gives_none_days_held():
    now = datetime(2025, 1, 1, tzinfo=timezone.utc)
    result = mp.compute_performance(
        current_value_usd=1000.0, initial_value_usd=900.0,
        uncollected_usd=10.0, collected_usd=5.0,
        first_seen_at_utc=None, now_utc=now,
    )
    assert result["days_held"] is None
    assert result["usd_per_day"] is None
    assert result["apr_percent"] is None
    # pnl_usd is still computable - it doesn't depend on days_held at all.
    assert result["pnl_usd"] == pytest.approx(1000.0 + 10.0 - 900.0)


# ── P/L excludes collected fees ───────────────────────────────────────────

def test_pnl_excludes_collected_fees():
    now = datetime(2025, 1, 1, tzinfo=timezone.utc)
    first_seen = now - timedelta(days=10)
    current_value_usd = 5000.0
    initial_value_usd = 4000.0
    uncollected_usd = 50.0
    collected_usd = 300.0  # large, non-zero - must NOT leak into pnl_usd

    result = mp.compute_performance(
        current_value_usd, initial_value_usd, uncollected_usd, collected_usd,
        first_seen, now,
    )
    expected_pnl = current_value_usd + uncollected_usd - initial_value_usd
    assert result["pnl_usd"] == pytest.approx(expected_pnl)
    assert result["pnl_usd"] != pytest.approx(expected_pnl + collected_usd)
    # total_earned_usd is a separate figure that DOES include collected.
    assert result["total_earned_usd"] == pytest.approx(collected_usd + uncollected_usd)


# ── Uncollected fee math, including uint256 wraparound ──────────────────

def test_fee_growth_inside_in_range():
    inside = mm.fee_growth_inside(
        current_tick=0, tick_lower=-10, tick_upper=10,
        fee_growth_global=1000, fee_growth_outside_lower=100, fee_growth_outside_upper=50,
    )
    assert inside == 850


def test_fee_growth_inside_wraparound_underflow():
    # fee_growth_outside_lower > fee_growth_global: the "feeGrowthGlobal -
    # feeGrowthOutside" subtraction underflows uint256 - this is EXPECTED
    # (per the Uniswap V3 accumulator design), masked rather than guarded.
    result = mm.fee_growth_inside(
        current_tick=-20, tick_lower=-10, tick_upper=10,
        fee_growth_global=5, fee_growth_outside_lower=100, fee_growth_outside_upper=2,
    )
    below_expected = (5 - 100) & mm.MASK_256
    expected = (5 - below_expected - 2) & mm.MASK_256
    assert result == expected
    assert 0 <= result <= mm.MASK_256  # stayed a valid uint256, never negative


def test_uncollected_fees_against_757217_style_fixture():
    # liquidity chosen so the fee-growth delta divides evenly, isolating
    # the formula's correctness from float/rounding concerns.
    liquidity = 2 ** 64
    fee_growth_inside_last = 500
    fee_growth_inside_current = fee_growth_inside_last + 2 ** 128  # delta = exactly 2**128
    tokens_owed = 42
    result = mm.uncollected_fees(liquidity, fee_growth_inside_current, fee_growth_inside_last, tokens_owed)
    assert result == liquidity + tokens_owed


def test_uncollected_fees_wraparound_delta():
    # fee_growth_inside_last > fee_growth_inside_current: the accumulator
    # itself wrapped between reads. Masked, not guarded - must not raise
    # and must not go negative.
    liquidity = 10
    result = mm.uncollected_fees(
        liquidity, fee_growth_inside_current=5, fee_growth_inside_last=10, tokens_owed=0
    )
    delta_expected = (5 - 10) & mm.MASK_256
    assert result == (liquidity * delta_expected) >> 128
    assert result >= 0


def test_value_position_wires_uncollected_and_collected_correctly():
    tick_lower, tick_upper, current_tick = -100, 100, 0
    sqrt_price_x96 = tick_to_sqrt_price_x96(current_tick)
    result = mp.value_position(
        liquidity=10 ** 18, tick_lower=tick_lower, tick_upper=tick_upper,
        current_tick=current_tick, sqrt_price_x96=sqrt_price_x96,
        decimals0=18, decimals1=18, token0_usd=2.0, token1_usd=3.0,
        uncollected0=1.5, uncollected1=2.5, collected0=0.5, collected1=0.25,
    )
    assert result["uncollected0"] == 1.5
    assert result["uncollected1"] == 2.5
    assert result["uncollected_usd"] == pytest.approx(1.5 * 2.0 + 2.5 * 3.0)
    assert result["collected_usd"] == pytest.approx(0.5 * 2.0 + 0.25 * 3.0)
    assert result["total_earned_usd"] == pytest.approx(result["collected_usd"] + result["uncollected_usd"])
    assert result["current_value_usd"] == pytest.approx(result["amount0_usd"] + result["amount1_usd"])


def test_value_position_none_prices_propagate_none_not_zero():
    result = mp.value_position(
        liquidity=10 ** 18, tick_lower=-100, tick_upper=100, current_tick=0,
        sqrt_price_x96=tick_to_sqrt_price_x96(0), decimals0=18, decimals1=18,
        token0_usd=None, token1_usd=None,
        uncollected0=1.0, uncollected1=1.0, collected0=1.0, collected1=1.0,
    )
    assert result["amount0_usd"] is None
    assert result["amount1_usd"] is None
    assert result["current_value_usd"] is None
    assert result["uncollected_usd"] is None
    assert result["collected_usd"] is None
    assert result["total_earned_usd"] is None
    # Token amounts themselves are still computed - a missing price doesn't
    # block the on-chain-math side of the valuation.
    assert result["amount0"] is not None
    assert result["amount1"] is not None


def test_sanity_check_price_within_tolerance():
    result = mp.sanity_check_price(100.0, 101.0, tolerance_frac=0.05)
    assert result["diverged"] is False
    assert result["ratio"] == pytest.approx(100.0 / 101.0)


def test_sanity_check_price_beyond_tolerance():
    result = mp.sanity_check_price(100.0, 50.0, tolerance_frac=0.05)
    assert result["diverged"] is True


def test_sanity_check_price_missing_input_is_none_not_false():
    result = mp.sanity_check_price(None, 100.0, tolerance_frac=0.05)
    assert result["diverged"] is None
    assert result["ratio"] is None


# ── Anchor resolver ────────────────────────────────────────────────────────

def test_anchor_resolver_miss_is_not_cached():
    # ETH has two references (base, ethereum) as of Phase D.2b - fail both
    # on the first call so the whole resolve misses, then succeed on the
    # very first reference tried on the second call.
    calls = []

    def failing_then_succeeding(ref_chain_id, ref_address, timeout=10):
        calls.append((ref_chain_id, ref_address))
        return None if len(calls) <= 2 else 2500.0

    r1 = ap.resolve_anchor_price("ETH", now=1000.0, fetcher=failing_then_succeeding)
    assert r1 == {"usd": None, "price_source": "unavailable", "age_seconds": None}

    # The miss must NOT have been cached - the very next call (still no TTL
    # elapsed) must attempt a fresh fetch, not reuse a cached miss.
    r2 = ap.resolve_anchor_price("ETH", now=1000.1, fetcher=failing_then_succeeding)
    assert r2["price_source"] == "live"
    assert r2["usd"] == 2500.0
    assert len(calls) == 3


def test_anchor_resolver_serves_stale_on_failure():
    def succeed(ref_chain_id, ref_address, timeout=10):
        return 2500.0

    r1 = ap.resolve_anchor_price("WETH", now=2000.0, fetcher=succeed)
    assert r1["price_source"] == "live"

    def fail(ref_chain_id, ref_address, timeout=10):
        return None

    r2 = ap.resolve_anchor_price("WETH", now=2000.0 + 61, fetcher=fail)  # past default 60s TTL
    assert r2["price_source"] == "stale"
    assert r2["usd"] == 2500.0
    assert r2["age_seconds"] == 61


def test_anchor_resolver_usdg_pins_to_one_when_no_external_price():
    def always_fail(asset):
        return None

    result = ap.resolve_anchor_price("USDG", now=3000.0, fetcher=always_fail)
    assert result == {"usd": 1.00, "price_source": "pinned", "age_seconds": None}


def test_anchor_resolver_usdg_uses_live_price_if_available():
    def succeed(asset):
        return 1.0005

    result = ap.resolve_anchor_price("USDG", now=4000.0, fetcher=succeed)
    assert result["price_source"] == "live"
    assert result["usd"] == 1.0005


def test_anchor_resolver_weth_and_eth_share_the_same_cache_entry():
    calls = []

    def succeed(ref_chain_id, ref_address, timeout=10):
        calls.append((ref_chain_id, ref_address))
        return 2500.0

    ap.resolve_anchor_price("WETH", now=5000.0, fetcher=succeed)
    r2 = ap.resolve_anchor_price("ETH", now=5000.1, fetcher=succeed)
    assert r2["price_source"] == "live"
    assert len(calls) == 1  # second call served from the shared ETH cache entry


def test_anchor_resolver_unknown_symbol_is_unavailable():
    result = ap.resolve_anchor_price("DOGE", now=6000.0, fetcher=lambda a: 1.0)
    assert result == {"usd": None, "price_source": "unavailable", "age_seconds": None}


# ── Phase D.2b: chain-filtered, liquidity-ranked, band-gated anchor pricing ──

def _pair(chain_id, address, price_usd, liquidity_usd):
    return {
        "chainId": chain_id,
        "baseToken": {"address": address},
        "priceUsd": price_usd,
        "liquidity": {"usd": liquidity_usd},
    }


_ETH_BASE_REF = ("base", "0x4200000000000000000000000000000000000006")
_ETH_MAINNET_REF = ("ethereum", "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2")


def test_anchor_resolver_eth_primary_reference_in_band_is_live():
    calls = []

    def fetcher(ref_chain_id, ref_address, timeout=10):
        calls.append((ref_chain_id, ref_address))
        assert (ref_chain_id, ref_address) == _ETH_BASE_REF
        return 2500.0

    result = ap.resolve_anchor_price("ETH", now=7000.0, fetcher=fetcher)
    assert result == {"usd": 2500.0, "price_source": "live", "age_seconds": 0}
    assert calls == [_ETH_BASE_REF]  # secondary reference never needed


def test_anchor_resolver_eth_primary_outside_band_falls_through_to_secondary():
    def fetcher(ref_chain_id, ref_address, timeout=10):
        if (ref_chain_id, ref_address) == _ETH_BASE_REF:
            return 0.00001277  # the exact production symptom - way outside the band
        return 2500.0

    result = ap.resolve_anchor_price("ETH", now=7100.0, fetcher=fetcher)
    assert result == {"usd": 2500.0, "price_source": "live", "age_seconds": 0}

    # The primary's bad value must never have been cached - if it had been,
    # a same-second re-resolve would serve 0.00001277 back as "live".
    assert ap._price_cache["ETH"] == (2500.0, 7100.0)


def test_anchor_resolver_eth_all_references_fail_band_is_unavailable():
    def fetcher(ref_chain_id, ref_address, timeout=10):
        return 0.00001277  # every reference produces an implausible price

    result = ap.resolve_anchor_price("ETH", now=7200.0, fetcher=fetcher)
    assert result == {"usd": None, "price_source": "unavailable", "age_seconds": None}
    assert "ETH" not in ap._price_cache


def test_select_best_pair_filters_out_wrong_chain_id_match():
    ref_chain_id, ref_address = _ETH_BASE_REF
    pairs = [
        # Same address, wrong chain - the exact D.2a defect this must reject.
        _pair("some-other-chain", ref_address, "0.00001277", 500.0),
    ]
    assert ap._select_best_pair(pairs, ref_chain_id, ref_address) is None


def test_select_best_pair_picks_highest_liquidity_among_same_chain_matches():
    ref_chain_id, ref_address = _ETH_BASE_REF
    pairs = [
        _pair(ref_chain_id, ref_address, "2400.0", 1_000.0),
        _pair(ref_chain_id, ref_address, "2500.0", 5_000_000.0),  # highest liquidity wins
        _pair(ref_chain_id, ref_address, "2450.0", 250_000.0),
    ]
    assert ap._select_best_pair(pairs, ref_chain_id, ref_address) == 2500.0


def test_anchor_resolver_usdc_always_pinned_regardless_of_depeg_fetcher():
    def in_band(ref_chain_id, ref_address, timeout=10):
        return 1.0

    result = ap.resolve_anchor_price("USDC", now=8000.0, fetcher=in_band)
    assert result == {"usd": 1.0, "price_source": "pinned", "age_seconds": 0}


def test_anchor_resolver_usdc_pinned_even_when_depeg_check_out_of_band():
    def out_of_band(ref_chain_id, ref_address, timeout=10):
        return 0.40  # would fail the USDC band, but must not affect the pin

    result = ap.resolve_anchor_price("USDC", now=8100.0, fetcher=out_of_band)
    assert result == {"usd": 1.0, "price_source": "pinned", "age_seconds": 0}


def test_anchor_resolver_usdc_pinned_even_when_depeg_check_raises():
    def raises(ref_chain_id, ref_address, timeout=10):
        raise RuntimeError("simulated depeg-check network failure")

    result = ap.resolve_anchor_price("USDC", now=8200.0, fetcher=raises)
    assert result == {"usd": 1.0, "price_source": "pinned", "age_seconds": 0}


def test_anchor_resolver_usdc_depeg_check_logs_warning_on_out_of_band_value(caplog):
    def out_of_band(ref_chain_id, ref_address, timeout=10):
        return 0.40

    with caplog.at_level("WARNING", logger="maxfi_anchor_prices"):
        ap.resolve_anchor_price("USDC", now=8300.0, fetcher=out_of_band)
    assert any("depeg" in rec.message.lower() for rec in caplog.records)


def test_anchor_resolver_usdg_still_pinned_unchanged():
    def always_fail(asset):
        return None

    result = ap.resolve_anchor_price("USDG", now=8400.0, fetcher=always_fail)
    assert result == {"usd": 1.00, "price_source": "pinned", "age_seconds": None}


def test_anchor_resolver_eth_band_settings_override_changes_what_passes(monkeypatch):
    # 2500.0 fails a code-default-tightened override band...
    overrides = {"maxfi_price_band_eth_min": 3000.0, "maxfi_price_band_eth_max": 4000.0}

    def fake_setting(key, default):
        return overrides.get(key, default)

    monkeypatch.setattr(ap, "_setting", fake_setting)

    def fetcher(ref_chain_id, ref_address, timeout=10):
        return 2500.0

    result = ap.resolve_anchor_price("ETH", now=9000.0, fetcher=fetcher)
    assert result == {"usd": None, "price_source": "unavailable", "age_seconds": None}

    ap._price_cache.clear()

    # ...but the same 2500.0 passes once the override band is widened back
    # down to include it, proving the settings key actually took effect.
    overrides["maxfi_price_band_eth_min"] = 500.0
    overrides["maxfi_price_band_eth_max"] = 20000.0
    result2 = ap.resolve_anchor_price("ETH", now=9100.0, fetcher=fetcher)
    assert result2 == {"usd": 2500.0, "price_source": "live", "age_seconds": 0}


def test_anchor_resolver_eth_stale_cache_passing_band_is_served_stale():
    def succeed(ref_chain_id, ref_address, timeout=10):
        return 2500.0

    ap.resolve_anchor_price("ETH", now=10_000.0, fetcher=succeed)

    def fail(ref_chain_id, ref_address, timeout=10):
        return None

    result = ap.resolve_anchor_price("ETH", now=10_000.0 + 61, fetcher=fail)
    assert result == {"usd": 2500.0, "price_source": "stale", "age_seconds": 61}


def test_anchor_resolver_eth_stale_cache_failing_band_is_unavailable_not_stale(monkeypatch):
    def succeed(ref_chain_id, ref_address, timeout=10):
        return 2500.0

    ap.resolve_anchor_price("ETH", now=11_000.0, fetcher=succeed)

    # Tighten the band via settings after caching, so the cached 2500.0 no
    # longer qualifies once TTL expires and a fresh fetch also fails.
    overrides = {"maxfi_price_band_eth_min": 3000.0, "maxfi_price_band_eth_max": 4000.0}
    monkeypatch.setattr(ap, "_setting", lambda key, default: overrides.get(key, default))

    def fail(ref_chain_id, ref_address, timeout=10):
        return None

    result = ap.resolve_anchor_price("ETH", now=11_000.0 + 61, fetcher=fail)
    assert result == {"usd": None, "price_source": "unavailable", "age_seconds": None}
